<?php

namespace Database\Seeders;

use App\Models\Prestasi;
use App\Models\User;
use Illuminate\Database\Seeder;

class PrestasiSeeder extends Seeder
{
    public function run(): void
    {
        $userId = User::first()->id ?? 1;

        $prestasis = [
            [
                'judul' => 'Juara II KSM Mapel Matematika terintegrasi',
                'peraih' => 'Naufal Kurnia Abdi',
                'kelas' => 'XII MIPA',
                'tingkat' => 'kabupaten',
                'jenis' => 'akademik',
                'tahun' => 2022,
                'tanggal_prestasi' => '2022-08-18',
                'penyelenggara' => 'Kemenag Kabupaten Batang',
                'is_featured' => true,
            ],
            [
                'judul' => 'Juara Harapan 1 KSM Mapel Fisika terintegrasi',
                'peraih' => 'Sekar Cahya Ningrum',
                'kelas' => 'XII MIPA',
                'tingkat' => 'kabupaten',
                'jenis' => 'akademik',
                'tahun' => 2022,
                'tanggal_prestasi' => '2022-08-18',
                'penyelenggara' => 'Kemenag Kabupaten Batang',
                'is_featured' => false,
            ],
            [
                'judul' => 'Juara Harapan 1 KSM Mapel Ekonomi terintegrasi',
                'peraih' => 'Mahdalista Nadlifatulaisy',
                'kelas' => 'XII IPS',
                'tingkat' => 'kabupaten',
                'jenis' => 'akademik',
                'tahun' => 2022,
                'tanggal_prestasi' => '2022-08-18',
                'penyelenggara' => 'Kemenag Kabupaten Batang',
                'is_featured' => false,
            ],
            [
                'judul' => 'Juara Harapan 2 KSM Mapel Biologi terintegrasi',
                'peraih' => 'Naila Herawaty Esafa',
                'kelas' => 'XII MIPA',
                'tingkat' => 'kabupaten',
                'jenis' => 'akademik',
                'tahun' => 2022,
                'tanggal_prestasi' => '2022-08-18',
                'penyelenggara' => 'Kemenag Kabupaten Batang',
                'is_featured' => false,
            ],
            [
                'judul' => 'Juara III Lomba baca puisi kategori umum dalam rangka pekan raya Batang 2022',
                'peraih' => 'Serly Rahmasari',
                'kelas' => 'XII MIPA',
                'tingkat' => 'kabupaten',
                'jenis' => 'non_akademik',
                'tahun' => 2022,
                'tanggal_prestasi' => '2022-09-02',
                'penyelenggara' => 'Kepala Dinas Perpustakaan dan kearsipan kabupaten Batang',
                'is_featured' => false,
            ],
            [
                'judul' => 'Peringkat 10 street parade klassen senior Brass HB Cup 2022',
                'peraih' => 'Marching Band Gema Surya Nada',
                'kelas' => 'MBGSN',
                'tingkat' => 'nasional',
                'jenis' => 'non_akademik',
                'tahun' => 2022,
                'tanggal_prestasi' => '2022-10-21',
                'penyelenggara' => 'PDBI Provinsi D.I. Yogyakarta',
                'is_featured' => true,
            ],
            [
                'judul' => 'Peraih Medali emas tingkat Nasional mapel kimia',
                'peraih' => 'Anis Nazilah',
                'kelas' => 'X IPS',
                'tingkat' => 'nasional',
                'jenis' => 'akademik',
                'tahun' => 2022,
                'tanggal_prestasi' => '2022-11-05',
                'penyelenggara' => 'Sigma Sains Indonesia',
                'is_featured' => true,
            ],
            [
                'judul' => 'Peraih Medali emas Madrasah Indonesia Olympiad Mapel Qur\'an Hadits',
                'peraih' => 'Nailil Muna',
                'kelas' => 'XII IPS',
                'tingkat' => 'provinsi',
                'jenis' => 'akademik',
                'tahun' => 2022,
                'tanggal_prestasi' => '2022-11-13',
                'penyelenggara' => 'Kementerian Agama KKMTS Provinsi Jawa Tengah',
                'is_featured' => true,
            ],
            [
                'judul' => 'Peraih Medali emas Madrasah Indonesia Olympiad Mapel TIK',
                'peraih' => 'Rahadian Candra Vima Yoga',
                'kelas' => 'XII MIPA',
                'tingkat' => 'provinsi',
                'jenis' => 'akademik',
                'tahun' => 2022,
                'tanggal_prestasi' => '2022-11-13',
                'penyelenggara' => 'Kementerian Agama KKMTS Provinsi Jawa Tengah',
                'is_featured' => true,
            ],
            [
                'judul' => 'Peraih medali perunggu Madrasah Indonesia Olympiad Mapel kimia',
                'peraih' => 'Nadin Okta Maema',
                'kelas' => 'XII MIPA',
                'tingkat' => 'provinsi',
                'jenis' => 'akademik',
                'tahun' => 2022,
                'tanggal_prestasi' => '2022-11-13',
                'penyelenggara' => 'Kementerian Agama KKMTS Provinsi Jawa Tengah',
                'is_featured' => false,
            ],
            [
                'judul' => 'Peraih medali perunggu Madrasah Indonesia Olympiad Mapel kimia',
                'peraih' => 'Dwi Indah Setiawati',
                'kelas' => 'XI MIPA',
                'tingkat' => 'provinsi',
                'jenis' => 'akademik',
                'tahun' => 2022,
                'tanggal_prestasi' => '2022-11-13',
                'penyelenggara' => 'Kementerian Agama KKMTS Provinsi Jawa Tengah',
                'is_featured' => false,
            ],
            [
                'judul' => 'Juara 1 Lomba Drumband/Marchingband MA HAB Kemenag',
                'peraih' => 'Marching Band Gema Surya Nada',
                'kelas' => 'MBGSN',
                'tingkat' => 'kabupaten',
                'jenis' => 'non_akademik',
                'tahun' => 2022,
                'tanggal_prestasi' => '2022-12-13',
                'penyelenggara' => 'Kemenag Kabupaten Batang',
                'is_featured' => true,
            ],
            [
                'judul' => 'Peraih Medali Perunggu Dalton Nasional Science Competition Mapel Kimia',
                'peraih' => 'Anis Nazilah',
                'kelas' => 'XII IPS',
                'tingkat' => 'nasional',
                'jenis' => 'akademik',
                'tahun' => 2023,
                'tanggal_prestasi' => '2023-01-14',
                'penyelenggara' => 'Dalton Olimpiad',
                'is_featured' => true,
            ],
            [
                'judul' => 'Juara 1 KSM Mapel Geografi terintegrasi',
                'peraih' => 'Dwi Nazifatul Sakinah',
                'kelas' => 'XI IPS',
                'tingkat' => 'kabupaten',
                'jenis' => 'akademik',
                'tahun' => 2023,
                'tanggal_prestasi' => '2023-07-10',
                'penyelenggara' => 'Kemenag Kabupaten Batang',
                'is_featured' => true,
            ],
            [
                'judul' => 'Juara 4 KSM Mapel Matematika terintegrasi',
                'peraih' => 'Isabela Aurely Noorma Devi',
                'kelas' => 'XI MIPA',
                'tingkat' => 'kabupaten',
                'jenis' => 'akademik',
                'tahun' => 2023,
                'tanggal_prestasi' => '2023-07-10',
                'penyelenggara' => 'Kemenag Kabupaten Batang',
                'is_featured' => false,
            ],
            [
                'judul' => 'Juara 5 KSM Mapel Ekonomi terintegrasi',
                'peraih' => 'Muhammad Fajar Adilwan',
                'kelas' => 'XI IPS',
                'tingkat' => 'kabupaten',
                'jenis' => 'akademik',
                'tahun' => 2023,
                'tanggal_prestasi' => '2023-07-10',
                'penyelenggara' => 'Kemenag Kabupaten Batang',
                'is_featured' => false,
            ],
            [
                'judul' => 'Juara 1 Drum Band tingkat pelajar SMA/SMK/MA/Umum dalam rangka Hari jadi ke-57 Kabupaten Batang',
                'peraih' => 'Marching Band Gema Surya Nada',
                'kelas' => 'MBGSN Ekskul',
                'tingkat' => 'kabupaten',
                'jenis' => 'non_akademik',
                'tahun' => 2023,
                'tanggal_prestasi' => '2023-03-18',
                'penyelenggara' => 'Bupati Batang',
                'is_featured' => true,
            ],
            [
                'judul' => 'Juara II Lomba pionering putra tingkat penghela lomba Pandu Tangguh Gerakan Kepanduan Hizbul Wathan',
                'peraih' => 'Ekstrakurikuler Hizbul Wathan',
                'kelas' => 'Ekskul HW',
                'tingkat' => 'kwarda',
                'jenis' => 'non_akademik',
                'tahun' => 2023,
                'tanggal_prestasi' => '2023-11-16',
                'penyelenggara' => 'Kwarda Batang',
                'is_featured' => true,
            ],
            [
                'judul' => 'Juara 1 Lomba Vlog Putri Tingkat Penghela Lomba Pandu Tangguh Gerakan Kepanduan Hizbul Wathan',
                'peraih' => 'Ekstrakurikuler Hizbul Wathan',
                'kelas' => 'Ekskul HW',
                'tingkat' => 'kwarda',
                'jenis' => 'non_akademik',
                'tahun' => 2024,
                'tanggal_prestasi' => '2024-11-08',
                'penyelenggara' => 'Kwarda Batang',
                'is_featured' => false,
            ],
            [
                'judul' => 'Juara III Lomba PBB Putra Tingkat Penghela Lomba Pandu Tangguh Gerakan Kepanduan Hizbul Wathan',
                'peraih' => 'Ekstrakurikuler Hizbul Wathan',
                'kelas' => 'Ekskul HW',
                'tingkat' => 'kwarda',
                'jenis' => 'non_akademik',
                'tahun' => 2024,
                'tanggal_prestasi' => '2024-11-08',
                'penyelenggara' => 'Kwarda Batang',
                'is_featured' => false,
            ],
            [
                'judul' => 'Juara III Lomba PBB Putri Tingkat Penghela Lomba Pandu Tangguh Gerakan Kepanduan Hizbul Wathan',
                'peraih' => 'Ekstrakurikuler Hizbul Wathan',
                'kelas' => 'Ekskul HW',
                'tingkat' => 'kwarda',
                'jenis' => 'non_akademik',
                'tahun' => 2024,
                'tanggal_prestasi' => '2024-11-08',
                'penyelenggara' => 'Kwarda Batang',
                'is_featured' => false,
            ],
            [
                'judul' => 'Juara 3 Lomba video konten literasi',
                'peraih' => 'Adzkia Ghifari Akhsan Muhammad',
                'kelas' => 'XI B',
                'tingkat' => 'kabupaten',
                'jenis' => 'non_akademik',
                'tahun' => 2025,
                'tanggal_prestasi' => '2025-03-04',
                'penyelenggara' => 'Dinas Perpustakaan dan Kearsipan Kab. Batang',
                'is_featured' => false,
            ],
            [
                'judul' => 'Juara I Lomba Pidato Bahasa Arab pada Ajang Porseni Madrasah Aliyah',
                'peraih' => 'Karimatul Zulfa Aulia',
                'kelas' => 'XII A',
                'tingkat' => 'kabupaten',
                'jenis' => 'akademik',
                'tahun' => 2025,
                'tanggal_prestasi' => '2025-06-19',
                'penyelenggara' => 'Kemenag Kabupaten Batang',
                'is_featured' => true,
            ],
            [
                'judul' => 'Peserta OSN Tahun 2025 Lolos tingkat Provinsi Mapel Kebumian',
                'peraih' => 'M. Rifqi Andrian',
                'kelas' => 'XII B',
                'tingkat' => 'kabupaten',
                'jenis' => 'akademik',
                'tahun' => 2025,
                'tanggal_prestasi' => '2025-07-13',
                'penyelenggara' => 'Dinas Pendidikan dan Kebudayaan Kab. Batang',
                'is_featured' => false,
            ],
            [
                'judul' => 'Peserta OSN Tahun 2025 Lolos tingkat Provinsi Mapel Kimia',
                'peraih' => 'Nazifa Nurin Shabrina',
                'kelas' => 'XII A',
                'tingkat' => 'kabupaten',
                'jenis' => 'akademik',
                'tahun' => 2025,
                'tanggal_prestasi' => '2025-07-13',
                'penyelenggara' => 'Dinas Pendidikan dan Kebudayaan Kab. Batang',
                'is_featured' => false,
            ],
            [
                'judul' => 'Peserta OSN Tahun 2025 Lolos tingkat Provinsi Mapel Astronomi',
                'peraih' => 'M. Irfan Pratama',
                'kelas' => 'XII A',
                'tingkat' => 'kabupaten',
                'jenis' => 'akademik',
                'tahun' => 2025,
                'tanggal_prestasi' => '2025-07-13',
                'penyelenggara' => 'Dinas Pendidikan dan Kebudayaan Kab. Batang',
                'is_featured' => false,
            ],
            [
                'judul' => 'Juara 1 Lomba Pembuatan Resensi Buku Berbasis Koleksi Perpustakaan',
                'peraih' => 'Musa An Nabiel',
                'kelas' => 'XII A',
                'tingkat' => 'kabupaten',
                'jenis' => 'akademik',
                'tahun' => 2025,
                'tanggal_prestasi' => '2025-09-01',
                'penyelenggara' => 'Dinas Perpustakaan dan Kearsipan Kab. Batang',
                'is_featured' => true,
            ],
            [
                'judul' => 'Juara 2 Olimpiade Kimia MA/SMA',
                'peraih' => 'Aufa Shalza Dhyanisha',
                'kelas' => 'XI A',
                'tingkat' => 'kabupaten',
                'jenis' => 'akademik',
                'tahun' => 2025,
                'tanggal_prestasi' => '2025-09-19',
                'penyelenggara' => 'Kemenag Kabupaten Batang',
                'is_featured' => false,
            ],
            [
                'judul' => 'Juara III POPDA Pencak Silat Kelas G Putra',
                'peraih' => 'Kaisa Arsyada Mukhlis',
                'kelas' => 'XI A',
                'tingkat' => 'kabupaten',
                'jenis' => 'non_akademik',
                'tahun' => 2025,
                'tanggal_prestasi' => '2025-11-06',
                'penyelenggara' => 'Dinas Pemuda dan Olahraga Kabupaten Batang',
                'is_featured' => false,
            ],
            [
                'judul' => 'Juara III POPDA Pencak Silat Kelas A Putri',
                'peraih' => 'Wahyu Indah Zafira',
                'kelas' => 'XI A',
                'tingkat' => 'kabupaten',
                'jenis' => 'non_akademik',
                'tahun' => 2025,
                'tanggal_prestasi' => '2025-11-06',
                'penyelenggara' => 'Dinas Pemuda dan Olahraga Kabupaten Batang',
                'is_featured' => false,
            ],
            [
                'judul' => 'Peraih medali perunggu pada Jateng Science Competition',
                'peraih' => 'Tim Guru Mualim',
                'kelas' => 'Guru',
                'tingkat' => 'provinsi',
                'jenis' => 'akademik',
                'tahun' => 2025,
                'tanggal_prestasi' => '2025-12-15',
                'penyelenggara' => 'Kemenag Wilayah Jawa Tengah',
                'is_featured' => true,
            ],
            [
                'judul' => 'Juara III Kelas G pada kejuaraan Pencak Silat Open Bahurekso Cup 2',
                'peraih' => 'Kaisa Arsyada Mukhlis',
                'kelas' => 'XI A',
                'tingkat' => 'kabupaten',
                'jenis' => 'non_akademik',
                'tahun' => 2025,
                'tanggal_prestasi' => '2025-12-22',
                'penyelenggara' => 'IPSI Kabupaten Pekalongan',
                'is_featured' => false,
            ],
            [
                'judul' => 'Juara II Kelas B pada kejuaraan Pencak Silat Open Bahurekso Cup 2',
                'peraih' => 'Wahyu Indah Zafira',
                'kelas' => 'XI A',
                'tingkat' => 'kabupaten',
                'jenis' => 'non_akademik',
                'tahun' => 2025,
                'tanggal_prestasi' => '2025-12-22',
                'penyelenggara' => 'IPSI Kabupaten Pekalongan',
                'is_featured' => false,
            ],
            [
                'judul' => 'Juara II Kelas B Putri Remaja pada Kejuaraan Pencak Silat Open',
                'peraih' => 'Rahma Jenny Amelia',
                'kelas' => 'XI B',
                'tingkat' => 'kabupaten',
                'jenis' => 'non_akademik',
                'tahun' => 2026,
                'tanggal_prestasi' => '2026-01-05',
                'penyelenggara' => 'DISPARPORA Kabupaten Batang',
                'is_featured' => false,
            ],
            [
                'judul' => 'Juara III Kelas A Putri Remaja pada kejuaraan Pencak Silat Open',
                'peraih' => 'Jihan Salma Salsabila',
                'kelas' => 'X B',
                'tingkat' => 'kabupaten',
                'jenis' => 'non_akademik',
                'tahun' => 2026,
                'tanggal_prestasi' => '2026-01-05',
                'penyelenggara' => 'DISPARPORA Kabupaten Batang',
                'is_featured' => false,
            ],
            [
                'judul' => 'Juara III Lomba Lari 400 M Putri Tingkat SMA/MA/SMK Muhammadiyah Se-Kabupaten Batang',
                'peraih' => 'Rahma Jenny Amelia',
                'kelas' => 'XI B',
                'tingkat' => 'kabupaten',
                'jenis' => 'non_akademik',
                'tahun' => 2026,
                'tanggal_prestasi' => '2026-01-11',
                'penyelenggara' => 'Pimpinan Daerah Muhammadiyah Batang',
                'is_featured' => false,
            ],
            [
                'judul' => 'Juara 2 Tartil Tingkat SMA/MA/SMK Muhammadiyah Se Kabupaten Batang',
                'peraih' => 'Adam Wafi Al Hudzaifah',
                'kelas' => 'XII A',
                'tingkat' => 'kabupaten',
                'jenis' => 'akademik',
                'tahun' => 2026,
                'tanggal_prestasi' => '2026-01-11',
                'penyelenggara' => 'Pimpinan Daerah Muhammadiyah Batang',
                'is_featured' => false,
            ],
            [
                'judul' => 'Juara 2 dalam rangka Turnamen AP Trofeo Futsal',
                'peraih' => 'Tim Futsal Mualim',
                'kelas' => 'Ekskul Futsal',
                'tingkat' => 'umum',
                'jenis' => 'non_akademik',
                'tahun' => 2026,
                'tanggal_prestasi' => '2026-02-01',
                'penyelenggara' => 'AP Trofeo Futsal',
                'is_featured' => false,
            ],
        ];

        foreach ($prestasis as $data) {
            $data['user_id'] = $userId;
            Prestasi::updateOrCreate(
                ['judul' => $data['judul'], 'peraih' => $data['peraih']],
                $data
            );
        }
    }
}
